version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    container_name: portfolio-lp
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: portfolio-lp_mysql
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
      
volumes:
    db_data: